# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: langid.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='langid.proto',
  package='langid',
  serialized_pb='\n\x0clangid.proto\x12\x06langid\"\xeb\x01\n\x12LanguageIdentifier\x12\x11\n\tnum_feats\x18\x01 \x02(\x05\x12\x11\n\tnum_langs\x18\x02 \x02(\x05\x12\x12\n\nnum_states\x18\x03 \x02(\x05\x12\x17\n\x0btk_nextmove\x18\x04 \x03(\x05\x42\x02\x10\x01\x12\x17\n\x0btk_output_c\x18\x05 \x03(\x05\x42\x02\x10\x01\x12\x17\n\x0btk_output_s\x18\x06 \x03(\x05\x42\x02\x10\x01\x12\x15\n\ttk_output\x18\x07 \x03(\x05\x42\x02\x10\x01\x12\x11\n\x05nb_pc\x18\x08 \x03(\x01\x42\x02\x10\x01\x12\x12\n\x06nb_ptc\x18\t \x03(\x01\x42\x02\x10\x01\x12\x12\n\nnb_classes\x18\n \x03(\t')




_LANGUAGEIDENTIFIER = _descriptor.Descriptor(
  name='LanguageIdentifier',
  full_name='langid.LanguageIdentifier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_feats', full_name='langid.LanguageIdentifier.num_feats', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_langs', full_name='langid.LanguageIdentifier.num_langs', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_states', full_name='langid.LanguageIdentifier.num_states', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tk_nextmove', full_name='langid.LanguageIdentifier.tk_nextmove', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
    _descriptor.FieldDescriptor(
      name='tk_output_c', full_name='langid.LanguageIdentifier.tk_output_c', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
    _descriptor.FieldDescriptor(
      name='tk_output_s', full_name='langid.LanguageIdentifier.tk_output_s', index=5,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
    _descriptor.FieldDescriptor(
      name='tk_output', full_name='langid.LanguageIdentifier.tk_output', index=6,
      number=7, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
    _descriptor.FieldDescriptor(
      name='nb_pc', full_name='langid.LanguageIdentifier.nb_pc', index=7,
      number=8, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
    _descriptor.FieldDescriptor(
      name='nb_ptc', full_name='langid.LanguageIdentifier.nb_ptc', index=8,
      number=9, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
    _descriptor.FieldDescriptor(
      name='nb_classes', full_name='langid.LanguageIdentifier.nb_classes', index=9,
      number=10, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=25,
  serialized_end=260,
)

DESCRIPTOR.message_types_by_name['LanguageIdentifier'] = _LANGUAGEIDENTIFIER

class LanguageIdentifier(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LANGUAGEIDENTIFIER

  # @@protoc_insertion_point(class_scope:langid.LanguageIdentifier)


_LANGUAGEIDENTIFIER.fields_by_name['tk_nextmove'].has_options = True
_LANGUAGEIDENTIFIER.fields_by_name['tk_nextmove']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
_LANGUAGEIDENTIFIER.fields_by_name['tk_output_c'].has_options = True
_LANGUAGEIDENTIFIER.fields_by_name['tk_output_c']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
_LANGUAGEIDENTIFIER.fields_by_name['tk_output_s'].has_options = True
_LANGUAGEIDENTIFIER.fields_by_name['tk_output_s']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
_LANGUAGEIDENTIFIER.fields_by_name['tk_output'].has_options = True
_LANGUAGEIDENTIFIER.fields_by_name['tk_output']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
_LANGUAGEIDENTIFIER.fields_by_name['nb_pc'].has_options = True
_LANGUAGEIDENTIFIER.fields_by_name['nb_pc']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
_LANGUAGEIDENTIFIER.fields_by_name['nb_ptc'].has_options = True
_LANGUAGEIDENTIFIER.fields_by_name['nb_ptc']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
# @@protoc_insertion_point(module_scope)
