/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: langid.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "langid.pb-c.h"
void   langid__language_identifier__init
                     (Langid__LanguageIdentifier         *message)
{
  static Langid__LanguageIdentifier init_value = LANGID__LANGUAGE_IDENTIFIER__INIT;
  *message = init_value;
}
size_t langid__language_identifier__get_packed_size
                     (const Langid__LanguageIdentifier *message)
{
  assert(message->base.descriptor == &langid__language_identifier__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t langid__language_identifier__pack
                     (const Langid__LanguageIdentifier *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &langid__language_identifier__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t langid__language_identifier__pack_to_buffer
                     (const Langid__LanguageIdentifier *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &langid__language_identifier__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Langid__LanguageIdentifier *
       langid__language_identifier__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Langid__LanguageIdentifier *)
     protobuf_c_message_unpack (&langid__language_identifier__descriptor,
                                allocator, len, data);
}
void   langid__language_identifier__free_unpacked
                     (Langid__LanguageIdentifier *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &langid__language_identifier__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor langid__language_identifier__field_descriptors[10] =
{
  {
    "num_feats",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Langid__LanguageIdentifier, num_feats),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_langs",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Langid__LanguageIdentifier, num_langs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_states",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Langid__LanguageIdentifier, num_states),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tk_nextmove",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Langid__LanguageIdentifier, n_tk_nextmove),
    offsetof(Langid__LanguageIdentifier, tk_nextmove),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tk_output_c",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Langid__LanguageIdentifier, n_tk_output_c),
    offsetof(Langid__LanguageIdentifier, tk_output_c),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tk_output_s",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Langid__LanguageIdentifier, n_tk_output_s),
    offsetof(Langid__LanguageIdentifier, tk_output_s),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tk_output",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Langid__LanguageIdentifier, n_tk_output),
    offsetof(Langid__LanguageIdentifier, tk_output),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nb_pc",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Langid__LanguageIdentifier, n_nb_pc),
    offsetof(Langid__LanguageIdentifier, nb_pc),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nb_ptc",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Langid__LanguageIdentifier, n_nb_ptc),
    offsetof(Langid__LanguageIdentifier, nb_ptc),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nb_classes",
    10,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Langid__LanguageIdentifier, n_nb_classes),
    offsetof(Langid__LanguageIdentifier, nb_classes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned langid__language_identifier__field_indices_by_name[] = {
  9,   /* field[9] = nb_classes */
  7,   /* field[7] = nb_pc */
  8,   /* field[8] = nb_ptc */
  0,   /* field[0] = num_feats */
  1,   /* field[1] = num_langs */
  2,   /* field[2] = num_states */
  3,   /* field[3] = tk_nextmove */
  6,   /* field[6] = tk_output */
  4,   /* field[4] = tk_output_c */
  5,   /* field[5] = tk_output_s */
};
static const ProtobufCIntRange langid__language_identifier__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor langid__language_identifier__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "langid.LanguageIdentifier",
  "LanguageIdentifier",
  "Langid__LanguageIdentifier",
  "langid",
  sizeof(Langid__LanguageIdentifier),
  10,
  langid__language_identifier__field_descriptors,
  langid__language_identifier__field_indices_by_name,
  1,  langid__language_identifier__number_ranges,
  (ProtobufCMessageInit) langid__language_identifier__init,
  NULL,NULL,NULL    /* reserved[123] */
};
